---
- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: File hello world
      copy:
        content: hello world - AS GRUPO 4 
        dest: /home/ubuntu/testfile.txt
    - name: Install nodejs
      apt:
        name: nodejs
        state: present

    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io','docker-compose']

    - name: Enable docker service at boot
      service:
        name: docker
        state: started
        enabled: yes

    - name: docker hello-world
      shell: "docker run hello-world"